### ISSUE TITLE
SDK must be initialized.

### ISSUE THREAD

**Issue by BrunoJurkovic** [oddbit/flutter_facebook_app_events#10]
## Current Behavior
When I build the app, it throws the error bellow.

## Steps to Reproduce (for bugs)
1. Build the app.

## Error
```
Caused by com.facebook.k: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
       at com.facebook.internal.Validate.a(Validate.java:11)
       at com.facebook.appevents.AppEventsLoggerImpl.<init>(AppEventsLoggerImpl.java:3)
       at com.facebook.appevents.AppEventsLoggerImpl.<init>(AppEventsLoggerImpl.java:4)
       at com.facebook.appevents.AppEventsLogger.<init>(AppEventsLogger.java:5)
       at com.facebook.appevents.AppEventsLogger.a(AppEventsLogger.java:3)
       at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.<init>(FacebookAppEventsPlugin.java:16)
       at i

id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin$Companion.registerWith(FacebookAppEventsPlugin.java:18)
       at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.a(FacebookAppEventsPlugin.java:2)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:13)
       at com.remade.fortbuddy.MainActivity.onCreate(MainActivity.java:6)
       at android.app.Activity.performCreate(Activity.java:7803)
       at android.app.Activity.performCreate(Activity.java:7792)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)```

**Comment by BrunoJurkovic** [comment]
The error was that the meta-data was located in the activity tag, but not in the application tag in the manifest.
