### ISSUE TITLE
Could not determine the dependencies of task ':facebook_app_events:compileDebugAidl'.

### ISSUE THREAD

**Issue by Feelthewind** [oddbit/flutter_facebook_app_events#17]
Could not determine the dependencies of task ':facebook_app_events:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':facebook_app_events:debugCompileClasspath'.
   > Could not find androidsdk.modules:shield:unspecified.
     Required by:
         project :facebook_app_events > com.facebook.android:facebook-core:5.15.2

## Expected Behavior
All the code worked last night, but it just started to crash with the above error message.

## Your Environment
* Output from `flutter doctor`
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.592], locale ko-KR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
[√] VS Code (version 1.41.1)
[√] Connected device (3 available)

* Operating System and version:
Windows 10 Pro

$ flutter run -v -d all
[  +26 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +35 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +20 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.5-0-g27321ebba
[   +9 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[   +3 ms] https://github.com/flutter/flutter.git
[  +50 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +93 ms] executing: C:\Users\lcs\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +18 ms] Exit code 0 from: C:\Users\lcs\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           ce0717175407044d0c     device product:dreamlteks model:SM_G950N device:dreamlteks transport_id:3
           emulator-5554          device product:sdk_gphone_x86_arm model:AOSP_on_IA_Emulator device:generic_x86_arm transport_id:4
           emulator-5556          device product:sdk_gphone_x86_arm model:AOSP_on_IA_Emulator device:generic_x86_arm transport_id:5
[  +11 ms] C:\Users\lcs\AppData\Local\Android\sdk\platform-tools\adb.exe -s ce0717175407044d0c shell getprop
[  +87 ms] C:\Users\lcs\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +35 ms] C:\Users\lcs\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5556 shell getprop
[  +42 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +40 ms] Found plugin barcode_scan at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\barcode_scan-1.0.0\
[  +25 ms] Found plugin contacts_service at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\contacts_service-0.2.9\
[  +10 ms] Found plugin facebook_app_events at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\facebook_app_events-0.5.0\
[   +3 ms] Found plugin firebase_messaging at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.9\
[   +8 ms] Found plugin flutter_secure_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_secure_storage-3.3.1+1\
[  +10 ms] Found plugin flutter_web_view at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_web_view-0.0.6\
[   +1 ms] Found plugin flutter_webview_plugin at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.3.8\
[   +8 ms] Found plugin iamport_flutter at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\iamport_flutter-0.9.8\
[  +13 ms] Found plugin kakao_flutter_sdk at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\kakao_flutter_sdk-0.3.2\
[  +18 ms] Found plugin package_info at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.0+13\
[  +10 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.5.1\
[   +1 ms] Found plugin permission_handler at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-4.1.0\
[  +18 ms] Found plugin share at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.3+5\
[   +9 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6\
[   +1 ms] Found plugin shared_preferences_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+3\
[   +1 ms] Found plugin shared_preferences_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+2\
[   +7 ms] Found plugin store_redirect at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\store_redirect-1.0.1\
[  +10 ms] Found plugin uni_links at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\uni_links-0.2.0\
[  +12 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.1\
[   +1 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+2\
[   +1 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.0+2\
[  +28 ms] Found plugin barcode_scan at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\barcode_scan-1.0.0\
[  +14 ms] Found plugin contacts_service at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\contacts_service-0.2.9\
[  +10 ms] Found plugin facebook_app_events at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\facebook_app_events-0.5.0\
[   +9 ms] Found plugin firebase_messaging at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-6.0.9\
[   +4 ms] Found plugin flutter_secure_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_secure_storage-3.3.1+1\
[  +13 ms] Found plugin flutter_web_view at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_web_view-0.0.6\
[   +1 ms] Found plugin flutter_webview_plugin at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_webview_plugin-0.3.8\
[   +6 ms] Found plugin iamport_flutter at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\iamport_flutter-0.9.8\
[  +11 ms] Found plugin kakao_flutter_sdk at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\kakao_flutter_sdk-0.3.2\
[   +9 ms] Found plugin package_info at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\package_info-0.4.0+13\
[   +6 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.5.1\
[   +3 ms] Found plugin permission_handler at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-4.1.0\
[  +19 ms] Found plugin share at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\share-0.6.3+5\
[   +8 ms] Found plugin shared_preferences at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.6\
[   +1 ms] Found plugin shared_preferences_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+3\
[   +1 ms] Found plugin shared_preferences_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+2\
[   +6 ms] Found plugin store_redirect at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\store_redirect-1.0.1\
[  +11 ms] Found plugin uni_links at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\uni_links-0.2.0\
[  +15 ms] Found plugin url_launcher at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.1\
[   +1 ms] Found plugin url_launcher_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+2\
[  +13 ms] Found plugin url_launcher_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.0+2\
[  +43 ms] Generating C:\Users\lcs\projects\coint_x_alpha\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +52 ms] ro.hardware = samsungexynos8895
[        ] ro.hardware = ranchu
[   +1 ms] Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[   +1 ms] ro.hardware = ranchu
[        ] Using hardware rendering with device AOSP on IA Emulator. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +19 ms] Launching lib\main.dart on SM G950N in debug mode...
[   +8 ms] executing: C:\Users\lcs\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree C:\Users\lcs\projects\coint_x_alpha\build\app\outputs\apk\app.apk AndroidManifest.xml
[  +18 ms] Exit code 0 from: C:\Users\lcs\AppData\Local\Android\sdk\build-tools\29.0.2\aapt dump xmltree C:\Users\lcs\projects\coint_x_alpha\build\app\outputs\apk\app.apk
AndroidManifest.xml
[  +20 ms] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x52
               A: android:versionName(0x0101021c)="2.0.82" (Raw: "2.0.82")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1d
               A: android:compileSdkVersionCodename(0x01010573)="10" (Raw: "10")
               A: package="me.coint.wallet" (Raw: "me.coint.wallet")
               A: platformBuildVersionCode=(type 0x10)0x1d
               A: platformBuildVersionName=(type 0x10)0xa
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x15
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1d
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.READ_CONTACTS" (Raw: "android.permission.READ_CONTACTS")
               E: uses-permission (line=15)
                 A: android:name(0x01010003)="android.permission.WRITE_CONTACTS" (Raw: "android.permission.WRITE_CONTACTS")
               E: uses-permission (line=16)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw: "android.permission.INTERNET")
               E: uses-permission (line=17)
                 A: android:name(0x01010003)="android.permission.CAMERA" (Raw: "android.permission.CAMERA")
               E: uses-permission (line=18)
                 A: android:name(0x01010003)="android.permission.ACCESS_NETWORK_STATE" (Raw: "android.permission.ACCESS_NETWORK_STATE")
               E: uses-permission (line=19)
                 A: android:name(0x01010003)="android.permission.WAKE_LOCK" (Raw: "android.permission.WAKE_LOCK")
               E: uses-permission (line=20)
                 A: android:name(0x01010003)="com.google.android.c2dm.permission.RECEIVE" (Raw: "com.google.android.c2dm.permission.RECEIVE")
               E: uses-permission (line=21)
                 A: android:name(0x01010003)="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" (Raw:
                 "com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE")
               E: uses-permission (line=22)
                 A: android:name(0x01010003)="android.permission.WRITE_EXTERNAL_STORAGE" (Raw: "android.permission.WRITE_EXTERNAL_STORAGE")
               E: uses-permission (line=23)
                 A: android:name(0x01010003)="android.permission.READ_PHONE_STATE" (Raw: "android.permission.READ_PHONE_STATE")
               E: uses-permission (line=24)
                 A: android:name(0x01010003)="android.permission.READ_EXTERNAL_STORAGE" (Raw: "android.permission.READ_EXTERNAL_STORAGE")
               E: application (line=26)
                 A: android:label(0x01010001)="肄붿씤?? (Raw: "肄붿씤??)
                 A: android:icon(0x01010002)=@0x7f0c0000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw: "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:allowBackup(0x01010280)=(type 0x12)0x0
                 A: android:fullBackupContent(0x010104eb)=(type 0x12)0x0
                 A: android:usesCleartextTraffic(0x010104ec)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory" (Raw: "androidx.core.app.CoreComponentFactory")
                 E: meta-data (line=35)
                   A: android:name(0x01010003)="com.facebook.sdk.ApplicationId" (Raw: "com.facebook.sdk.ApplicationId")
                   A: android:value(0x01010024)=@0x7f0d0040
                 E: activity (line=39)
                   A: android:theme(0x01010000)=@0x7f0e00c5
                   A: android:name(0x01010003)="me.coint.wallet.MainActivity" (Raw: "me.coint.wallet.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x400037b4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: meta-data (line=53)
                     A: android:name(0x01010003)="io.flutter.app.android.SplashScreenUntilFirstFrame" (Raw: "io.flutter.app.android.SplashScreenUntilFirstFrame")
                     A: android:value(0x01010024)=(type 0x12)0xffffffff
                   E: intent-filter (line=57)
                     E: action (line=58)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw: "android.intent.action.MAIN")
                     E: category (line=60)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw: "android.intent.category.LAUNCHER")
                   E: intent-filter (line=64)
                     E: action (line=65)
                       A: android:name(0x01010003)="android.intent.action.VIEW" (Raw: "android.intent.action.VIEW")
                     E: category (line=67)
                       A: android:name(0x01010003)="android.intent.category.DEFAULT" (Raw: "android.intent.category.DEFAULT")
                     E: category (line=68)
                       A: android:name(0x01010003)="android.intent.category.BROWSABLE" (Raw: "android.intent.category.BROWSABLE")
                     E: data (line=70)
                       A: android:scheme(0x01010027)="coint" (Raw: "coint")
                   E: intent-filter (line=74)
                     E: action (line=75)
                       A: android:name(0x01010003)="FLUTTER_NOTIFICATION_CLICK" (Raw: "FLUTTER_NOTIFICATION_CLICK")
                     E: category (line=77)
                       A: android:name(0x01010003)="android.intent.category.DEFAULT" (Raw: "android.intent.category.DEFAULT")
                 E: activity (line=80)
                   A: android:name(0x01010003)="com.apptreesoftware.flutterwebview.WebViewActivity" (Raw: "com.apptreesoftware.flutterwebview.WebViewActivity")
                 E: activity (line=82)
                   A: android:name(0x01010003)="com.apptreesoftware.barcodescan.BarcodeScannerActivity" (Raw: "com.apptreesoftware.barcodescan.BarcodeScannerActivity")
                 E: activity (line=83)
                   A: android:theme(0x01010000)=@0x7f0e017c
                   A: android:name(0x01010003)="com.kakao.sdk.flutter.TalkAuthCodeActivity" (Raw: "com.kakao.sdk.flutter.TalkAuthCodeActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x2
                 E: activity (line=88)
                   A: android:theme(0x01010000)=@0x7f0e017c
                   A: android:name(0x01010003)="com.kakao.sdk.flutter.AuthCodeCustomTabsActivity" (Raw: "com.kakao.sdk.flutter.AuthCodeCustomTabsActivity")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   A: android:launchMode(0x0101001d)=(type 0x10)0x2
                 E: service (line=94)
                   A: android:name(0x01010003)="io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService" (Raw:
                   "io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService")
                   E: intent-filter (line=95)
                     E: action (line=96)
                       A: android:name(0x01010003)="com.google.firebase.MESSAGING_EVENT" (Raw: "com.google.firebase.MESSAGING_EVENT")
                 E: service (line=99)
                   A: android:name(0x01010003)="com.google.firebase.components.ComponentDiscoveryService" (Raw: "com.google.firebase.components.ComponentDiscoveryService")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:directBootAware(0x01010505)=(type 0x12)0xffffffff
                   E: meta-data (line=103)
                     A: android:name(0x01010003)="com.google.firebase.components:io.flutter.plugins.firebasemessaging.FlutterFirebaseAppRegistrar" (Raw:
                     "com.google.firebase.components:io.flutter.plugins.firebasemessaging.FlutterFirebaseAppRegistrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                   E: meta-data (line=106)
                     A: android:name(0x01010003)="com.google.firebase.components:com.google.firebase.iid.Registrar" (Raw:
                     "com.google.firebase.components:com.google.firebase.iid.Registrar")
                     A: android:value(0x01010024)="com.google.firebase.components.ComponentRegistrar" (Raw: "com.google.firebase.components.ComponentRegistrar")
                 E: activity (line=111)
                   A: android:theme(0x01010000)=@0x01030007
                   A: android:name(0x01010003)="io.flutter.plugins.urllauncher.WebViewActivity" (Raw: "io.flutter.plugins.urllauncher.WebViewActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: meta-data (line=116)
                   A: android:name(0x01010003)="com.facebook.sdk.CodelessDebugLogEnabled" (Raw: "com.facebook.sdk.CodelessDebugLogEnabled")
                   A: android:value(0x01010024)=(type 0x12)0xffffffff
                 E: provider (line=120)
                   A: android:name(0x01010003)="androidx.core.content.FileProvider" (Raw: "androidx.core.content.FileProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="me.coint.wallet.fileprovider" (Raw: "me.coint.wallet.fileprovider")
                   A: android:grantUriPermissions(0x0101001b)=(type 0x12)0xffffffff
                   E: meta-data (line=125)
                     A: android:name(0x01010003)="android.support.FILE_PROVIDER_PATHS" (Raw: "android.support.FILE_PROVIDER_PATHS")
                     A: android:resource(0x01010025)=@0x7f100000
                 E: service (line=133)
                   A: android:name(0x01010003)="com.google.firebase.messaging.FirebaseMessagingService" (Raw: "com.google.firebase.messaging.FirebaseMessagingService")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   E: intent-filter (line=136)
                     A: android:priority(0x0101001c)=(type 0x10)0xfffffe0c
                     E: action (line=137)
                       A: android:name(0x01010003)="com.google.firebase.MESSAGING_EVENT" (Raw: "com.google.firebase.MESSAGING_EVENT")
                 E: receiver (line=141)
                   A: android:name(0x01010003)="com.google.firebase.iid.FirebaseInstanceIdReceiver" (Raw: "com.google.firebase.iid.FirebaseInstanceIdReceiver")
                   A: android:permission(0x01010006)="com.google.android.c2dm.permission.SEND" (Raw: "com.google.android.c2dm.permission.SEND")
                   A: android:exported(0x01010010)=(type 0x12)0xffffffff
                   E: intent-filter (line=145)
                     E: action (line=146)
                       A: android:name(0x01010003)="com.google.android.c2dm.intent.RECEIVE" (Raw: "com.google.android.c2dm.intent.RECEIVE")
                 E: provider (line=150)
                   A: android:name(0x01010003)="com.google.firebase.provider.FirebaseInitProvider" (Raw: "com.google.firebase.provider.FirebaseInitProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="me.coint.wallet.firebaseinitprovider" (Raw: "me.coint.wallet.firebaseinitprovider")
                   A: android:initOrder(0x0101001a)=(type 0x10)0x64
                 E: activity (line=156)
                   A: android:theme(0x01010000)=@0x01030010
                   A: android:name(0x01010003)="com.google.android.gms.common.api.GoogleApiActivity" (Raw: "com.google.android.gms.common.api.GoogleApiActivity")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                 E: meta-data (line=161)
                   A: android:name(0x01010003)="com.google.android.gms.version" (Raw: "com.google.android.gms.version")
                   A: android:value(0x01010024)=@0x7f090008
                 E: provider (line=173)
                   A: android:name(0x01010003)="com.facebook.internal.FacebookInitProvider" (Raw: "com.facebook.internal.FacebookInitProvider")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   A: android:authorities(0x01010018)="me.coint.wallet.FacebookInitProvider" (Raw: "me.coint.wallet.FacebookInitProvider")
                 E: receiver (line=178)
                   A: android:name(0x01010003)="com.facebook.CurrentAccessTokenExpirationBroadcastReceiver" (Raw: "com.facebook.CurrentAccessTokenExpirationBroadcastReceiver")
                   A: android:exported(0x01010010)=(type 0x12)0x0
                   E: intent-filter (line=181)
                     E: action (line=182)
                       A: android:name(0x01010003)="com.facebook.sdk.ACTION_CURRENT_ACCESS_TOKEN_CHANGED" (Raw: "com.facebook.sdk.ACTION_CURRENT_ACCESS_TOKEN_CHANGED")
[ +127 ms] executing: C:\Users\lcs\AppData\Local\Android\sdk\platform-tools\adb.exe -s ce0717175407044d0c shell -x logcat -v time -s flutter
[   +8 ms] executing: C:\Users\lcs\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +29 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as C:\Users\lcs\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\Users\lcs\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +18 ms] Building APK
[  +15 ms] Running Gradle task 'assembleDebug'...
[   +1 ms] gradle.properties already sets `android.enableR8`
[   +5 ms] Using gradle from C:\Users\lcs\projects\coint_x_alpha\android\gradlew.bat.
[  +12 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +91 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +2 ms] executing: [C:\Users\lcs\projects\coint_x_alpha\android\] C:\Users\lcs\projects\coint_x_alpha\android\gradlew.bat -Pverbose=true
-Ptarget=C:\Users\lcs\projects\coint_x_alpha\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64 assembleDebug
[+51393 ms] FAILURE: Build failed with an exception.
[   +4 ms] * What went wrong:
[   +5 ms] Could not determine the dependencies of task ':facebook_app_events:compileDebugAidl'.
[   +1 ms] > Could not resolve all task dependencies for configuration ':facebook_app_events:debugCompileClasspath'.
[        ]    > Could not find androidsdk.modules:shield:unspecified.
[        ]      Required by:
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
[        ]          project :facebook_app_events > com.facebook.android:facebook-core:5.15.2
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[   +9 ms] BUILD FAILED in 51s
[ +347 ms] Running Gradle task 'assembleDebug'... (completed in 51.9s)
[   +3 ms] "flutter run" took 52,991ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by DennisAlund** [comment]
Can you confirm that this is consistently breaking for you and directly linked to an error with the library?

**Comment by DennisAlund** [comment]
Is there any new information or progress on the troubleshooting of this issue? Or has it been resolved? Please share your learnings if it has been resolved by fixing external causes.

**Comment by DennisAlund** [comment]
Closing due to inactivity
