### ISSUE TITLE
Unhandled Exception: PlatformException

### ISSUE THREAD

**Issue by Zazo032** [oddbit/flutter_facebook_app_events#19]
Plugin version: 0.5.1
Flutter version: 1.15.4
Kotlin version: 1.3.61

We're sometimes seeing in the logs the following unhandled exception:

```kotlin
E/flutter (11731): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Unsupported value type: class java.util.ArrayList (Kotlin reflection is not available), null)
E/flutter (11731): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
E/flutter (11731): #1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
E/flutter (11731): <asynchronous suspension>
E/flutter (11731): #2 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329)
E/flutter (11731): #3 FacebookAppEvents.logEvent (package:facebook_app_events/facebook_app_events.dart:68)
** ellided info **
```

**Comment by DennisAlund** [comment]
Please provide some context on what values that you tried to pass into the functions. Could you provide the code part which causes this error to occur and also the values which you passed to the `logEvent`

**Comment by DennisAlund** [comment]
Closing due to inactivity

**Comment by Zazo032** [comment]
@DennisAlund Hi, this happens when this `Map` is provided to the `parameters` param, in the `logEvent` function:

```dart
final Map<String, dynamic> _params = <String, dynamic>{
  'content_category': 'Alicante',
  'content_name': 'Viena',
  'content_ids': <String>['alcvie'],
  'content_type': 'Alicante-Viena-Alicante',
};
```

To give some context, this is the method that throws the exception:

https://github.com/oddbit/flutter_facebook_app_events/blob/9c32747ba60beacc980d43146c6d3dc4f8c8e037/android/src/main/kotlin/id/oddbit/flutter/facebook_app_events/FacebookAppEventsPlugin.kt#L153-L181

```
java.lang.IllegalArgumentException: Unsupported value type: class java.util.ArrayList (Kotlin reflection is not available)
E/MethodChannel#flutter.oddbit.id/facebook_app_events(16471): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.createBundleFromMap(FacebookAppEventsPlugin.kt:176)
```
There's no `if` case for `ArrayList`.

Could you reopen this issue?

**Comment by olegys** [comment]
Same error on array:

    _facebookAppEvents.logEvent(
      name: 'AddToCart',
      valueToSum: _price,
      parameters: {
        'value': _price,
        'currency': 'UAH',
        'content_type': 'product',
        'content_ids': [product.id.toString()],
        'content_name': product.name,
        'content_category': product.type,
      },
    );

**Comment by olegys** [comment]
> Same error on array:
> 
> ```
> _facebookAppEvents.logEvent(
>   name: 'AddToCart',
>   valueToSum: _price,
>   parameters: {
>     'value': _price,
>     'currency': 'UAH',
>     'content_type': 'product',
>     'content_ids': [product.id.toString()],
>     'content_name': product.name,
>     'content_category': product.type,
>   },
> ); 
> ```
found a solution to this problem, can be sent by string:  "[\"1234\",\"5678\"]"

**Comment by DennisAlund** [comment]
I think this falls under developer responsibility in case it's a generic event, since it will depend on the parameter and what specifications of the content that is for that parameter type.

Please see examples where the JSON encoding has been built into the wrapper functions for some event logging
https://github.com/oddbit/flutter_facebook_app_events/blob/f5d4960907a66313c402a5689824799461d1d173/lib/facebook_app_events.dart#L201
