### ISSUE TITLE
 The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.

### ISSUE THREAD

**Issue by vaidehee** [oddbit/flutter_facebook_app_events#22]
I want to integrate this plugin but due to some reason this error is showing up while running in android, can anybody help?
i have followed all the guidelines from the plugin page  and i have added <meta-data> to manifest too.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.oroom, PID: 7620
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.oroom/com.oroom.MainActivity}: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
        at com.facebook.internal.Validate.sdkInitialized(Validate.java:146)
        at com.facebook.appevents.AppEventsLoggerImpl.<init>(AppEventsLoggerImpl.java:564)
        at com.facebook.appevents.AppEventsLoggerImpl.<init>(AppEventsLoggerImpl.java:554)
        at com.facebook.appevents.AppEventsLogger.<init>(AppEventsLogger.java:314)
        at com.facebook.appevents.AppEventsLogger.newLogger(AppEventsLogger.java:262)
        at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.<init>(FacebookAppEventsPlugin.kt:19)
        at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin$Companion.registerWith(FacebookAppEventsPlugin.kt:26)
        at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.registerWith(Unknown Source:2)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:39)
        at com.oroom.MainActivity.onCreate(MainActivity.kt:31)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by DennisAlund** [comment]
Please provide your code to show the manifest and how you are using the plugin.

**Comment by DennisAlund** [comment]
Please check https://github.com/roughike/flutter_facebook_login/issues/36 as a reference to see if that might be the case for you too.

**Comment by vaidehee** [comment]
i resolved this by adding this additional code to manifest file,
but in the README file the author has not mentioned that this has to be added,
i suggest to please update your README file. 


 <activity android:name="com.facebook.FacebookActivity"
            android:configChanges=
                "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:label="@string/app_name" />

        <activity android:name="com.facebook.CustomTabActivity" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>

**Comment by DennisAlund** [comment]
I am the author 😊

Are you perhaps also using the Facebook login? The manifest changes that you suggest are only mentioned in the Facebook login setup: https://developers.facebook.com/docs/facebook-login/android/

Please note that the [readme is referring to the official documentation](https://github.com/oddbit/flutter_facebook_app_events#configure-android) for Facebook SDK to ensure that you setup properly.
