### ISSUE TITLE
[Bug]: lateinit property appEventsLogger has not been initialized

### ISSUE THREAD

**Issue by athmora** [oddbit/flutter_facebook_app_events#247]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

```
E/MethodChannel#flutter.oddbit.id/facebook_app_events( 7566): Failed to handle method call
E/MethodChannel#flutter.oddbit.id/facebook_app_events( 7566): kotlin.UninitializedPropertyAccessException: lateinit property appEventsLogger has not been initialized
E/MethodChannel#flutter.oddbit.id/facebook_app_events( 7566): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.handleLogEvent(FacebookAppEventsPlugin.kt:120)
E/MethodChannel#flutter.oddbit.id/facebook_app_events( 7566): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.onMethodCall(FacebookAppEventsPlugin.kt:49)
E/MethodChannel#flutter.oddbit.id/facebook_app_events( 7566): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter.oddbit.id/facebook_app_events( 7566): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#flutter.oddbit.id/facebook_app_events( 7566): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:320)
E/MethodChannel#flutter.oddbit.id/facebook_app_events( 7566): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter.oddbit.id/facebook_app_events( 7566): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter.oddbit.id/facebook_app_events( 7566): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter.oddbit.id/facebook_app_events( 7566): 	at android.os.Looper.loop(Looper.java:223)
E/MethodChannel#flutter.oddbit.id/facebook_app_events( 7566): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#flutter.oddbit.id/facebook_app_events( 7566): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.oddbit.id/facebook_app_events( 7566): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#flutter.oddbit.id/facebook_app_events( 7566): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 7566): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, lateinit property appEventsLogger has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property appEventsLogger has not been initialized
E/flutter ( 7566): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.handleLogEvent(FacebookAppEventsPlugin.kt:120)
E/flutter ( 7566): 	at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.onMethodCall(FacebookAppEventsPlugin.kt:49)
E/flutter ( 7566): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/flutter ( 7566): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/flutter ( 7566): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:320)
E/flutter ( 7566): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/flutter ( 7566): 	at android.os.Handler.handleCallback(Handler.java:938)
E/flutter ( 7566): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/flutter ( 7566): 	at android.os.Looper.loop(Looper.java:223)
E/flutter ( 7566): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter ( 7566): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 7566): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter ( 7566): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter ( 7566): )
E/flutter ( 7566): #0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:607
E/flutter ( 7566): #1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:177
E/flutter ( 7566): <asynchronous suspension>
E/flutter ( 7566): #2      SegmentSv.track [NOTE]
package:kigui/…/app/segment_service.dart:51
E/flutter ( 7566): <asynchronous suspension>
E/flutter ( 7566):
```

[NOTE] package:kigui/…/app/segment_service.dart:51 in this file i run a function that contains the FacebookAppEvents().logEvent method.

### Expected Behavior

Run code whitout any errors.

### Steps To Reproduce

https://pub.dev/packages/facebook_app_events Get Starting complete.

run this somewhere in the code:
```
final _fbe = FacebookAppEvents();
    await _fbe.logEvent(
      name: "event",
      parameters: {
        "parameter":"x",
      },
    );
```

### Platform

Android

### Flutter Doctor

```shell
[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [VersiÃ³n 10.0.22000.739], locale es-AR)
    • Flutter version 2.10.3 at C:\flutter\2.10.3
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (4 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\Thomas\AppData\Local\Android\Sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\Thomas\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.2.5)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.2.32616.157
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2020.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code
    • VS Code at C:\Users\Thomas\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.44.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [VersiÃ³n 10.0.22000.739]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 103.0.5060.114
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 103.0.1264.37

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by anchliyatushar** [comment]
@athmora Try this. This might solve your issue - https://github.com/oddbit/flutter_facebook_app_events/issues/186#issuecomment-1123781314

**Comment by athmora** [comment]
@anchliyatushar I already tried it, and it is added in the project, but it still does not work

**Comment by athmora** [comment]
@anchliyatushar updated debug console. My bad, I didn't copy the entire content of the debug console, sorry

**Comment by DennisAlund** [comment]
Just want to check if you can help out with something, you ticked the checkbox of having searched the repo for similar issues: https://github.com/oddbit/flutter_facebook_app_events/search?q=UninitializedPropertyAccessException&type=issues

Can you help by clarifying what solutions from those issues that you have tried, what didn't work for you and how this issue might be different?

1. https://github.com/oddbit/flutter_facebook_app_events/issues/186
2. https://github.com/oddbit/flutter_facebook_app_events/issues/231
3. https://github.com/oddbit/flutter_facebook_app_events/issues/199
4. https://github.com/oddbit/flutter_facebook_app_events/issues/132

**Comment by athmora** [comment]
@DennisAlund Hello, thanks for the answer, attachment 3 found the solution, even so I should check if the events arrive at the facebook console, the error no longer appears, but I cannot confirm that the event is sent. tomorrow I will confirm this action and in the best of cases we will close this report, thank you very much

**Comment by athmora** [comment]
@DennisAlund It works. 
Closing the bug report by fix the problem.
Thank you so much.
