### ISSUE TITLE
[Bug]: Error happens if upgrade to   facebook_app_events: ^0.16.0 or higher

### ISSUE THREAD

**Issue by ldemyanenko** [oddbit/flutter_facebook_app_events#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On app start when Splash screen is showed there is an Firebase error
```
E/flutter (26891): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
E/flutter (26891): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (26891): <asynchronous suspension>
E/flutter (26891): #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:344:35)
E/flutter (26891): <asynchronous suspension>
E/flutter (26891): #2      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:31:23)
E/flutter (26891): <asynchronous suspension>
E/flutter (26891): #3      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:73:7)
E/flutter (26891): <asynchronous suspension>
E/flutter (26891): #4      Firebase.initializeApp (package:firebase_core/src/firebase.dart:42:31)
E/flutter (26891): <asynchronous suspension>
E/flutter (26891): #5      main (package:get_gaston/main.dart:26:3)
E/flutter (26891): <asynchronous suspension>
E/flutter (26891): 
```
```

### Expected Behavior

On version   facebook_app_events: ^0.14.0 or facebook_app_events: ^0.15.0 everything is fine. App is able to launch correctly and there is no conflict with Firebase.

### Steps To Reproduce

_No response_

### Platform

_No response_

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 12.3.1 21E258 darwin-arm, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[!] Android Studio (version 2020.3)
    ✗ Unable to find bundled Java version.
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by ldemyanenko** [comment]
It's Android only issue

**Comment by DennisAlund** [comment]
Your error log seems to indicate that you need to initialize something with Firebase. Have you updated other plugins at the same time?

**Comment by DennisAlund** [comment]
Please confirm if this issue is different from #81 or #52. Closing as a duplicate for now until more information provided on how this is a new issue not resolved in any of those two.
