### ISSUE TITLE
[Bug]: 0.19.3 Android: kotlin.UninitializedPropertyAccessException: lateinit property appEventsLogger has not been initialized

### ISSUE THREAD

**Issue by hhzhangzy** [oddbit/flutter_facebook_app_events#393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Install facebook_app_events: ^0.19.3 and configure Android manifest as documented with facebook_app_id and facebook_client_token
Call the ‘logPurchase‘ method
E/MethodChannel#flutter.oddbit.id/facebook_app_events( 2737): kotlin.UninitializedPropertyAccessException: lateinit property appEventsLogger has not been initialized.

### Expected Behavior

Expected that the plugin would initialize the Facebook SDK

### Steps To Reproduce

1.Install facebook_app_events: ^0.19.3[0.19.4, 0.19.2] 
2. configure Android manifest as documented with facebook_app_id and facebook_client_token
`<application android:label='xxxx'>
  <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
  ...
  <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
  <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>
</application >
`
, andriod/app/src/main/res/values and values-night/styles.xml
`
<resources>
    ...
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    ...
    <string name="facebook_app_id">xxx</string>  // xxx representing the configured FaceBook AppId
    <string name="facebook_client_token">xxxxxxx</string> // xxxxxxx representing the configured FaceBook  Token
</resources>
`

Test  in app:
`FacebookAppEvents().logPurchase(amount: 1.00, currency: 'USD');`

### Platform

Android

### Flutter Doctor

```shell
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [版本 10.0.22631.4460], locale zh-CN)
    • Flutter version 3.19.6 on channel stable at C:\Users\wangr\fvm\versions\3.19.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (7 months ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at D:\android SDK
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = D:\android SDK
    • Java binary at: C:\Users\wangr\Downloads\android-studio-2023.2.1.23-windows-exe\android-studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0--11185874)
    • All Android licenses accepted.

[√] Android Studio (version 2022.2)
    • Android Studio at D:\android
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "17.0.6" 2023-01-17

[√] Android Studio (version 2023.2)
    • Android Studio at C:\Users\wangr\Downloads\android-studio-2023.2.1.23-windows-exe\android-studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version openjdk version "17.0.9" 2023-10-17

[!] Connected device
    ! No devices available

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

**Comment by antonoddbit** [comment]
Hi @hhzhangzy have you tried put the line on some button and try try to click it?

**Comment by joaoarmando** [comment]
same here

**Comment by antonoddbit** [comment]
@joaoarmando could you put paste the code and show the files?

**Comment by joaoarmando** [comment]
I fixed by following https://stackoverflow.com/questions/70271507/facebook-app-events-not-working-in-flutter

**Comment by Mo0Khaled** [comment]
same here.

**Comment by enesakbal** [comment]
Update your style.xml file as below, maybe it will work

```xml
<resources>
  <string name="facebook_app_id">[APP_ID]</string>
  <string name="facebook_client_token">[CLIENT_TOKEN]</string>
  <string name="fb_login_protocol_scheme">fb[APP_ID]</string>
  <string name="app_name">[APP_NAME]</string>
</resources>
```

**Comment by wwnOddbit** [comment]
Would you try the latest version v0.19.5 ? Please kindly confirm if the issue has been resolved.

**Comment by danieeelfc** [comment]
0.19.5 and I get the following error on my crashlytics:
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
PlatformException(error, lateinit property appEventsLogger has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property appEventsLogger has not been initialized at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.handleLogEvent(FacebookAppEventsPlugin.kt:120) at id.oddbit.flutter.facebook_app_events.FacebookAppEventsPlugin.onMethodCall(FacebookAppEventsPlugin.kt:49) at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267) at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292) at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:319) at io.flutter.embedding.engine.dart.DartMessenger.$r8$lambda$2j2MERcK825A5j1fv5sZ7xB2Iuo(Unknown Source:0) at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12) at android.os.Handler.handleCallback(Handler.java:991) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loopOnce(Looper.java:232) at android.os.Looper.loop(Looper.java:317) at android.app.ActivityThread.main(ActivityThread.java:8787) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:871) )
```
