### ISSUE TITLE
Event manager black screen on android

### ISSUE THREAD

**Issue by olegys** [oddbit/flutter_facebook_app_events#70]
When I using 
facebook_app_events and use Codeless method
review screen show but it black like this:

![70728313-d98c8e80-1d09-11ea-910d-0ab923a57292](https://user-images.githubusercontent.com/18525409/102259083-56eb7000-3f17-11eb-944a-9a3da666d637.png)

**Comment by DennisAlund** [comment]
1. Please use provided issue templates.
2. Could you provide more context and information on how it looks "when it works" expectations etc (the issue template is providing the structure so that it's a complete problem description). 

Please update the issue with full context of what you expect and how it should work

**Comment by DennisAlund** [comment]
Closing due to inactivity

**Comment by kingmaster772** [comment]
This is what I get when shaking my phone for codeless setup on debug mode

![image](https://user-images.githubusercontent.com/29949806/165689314-bb92a208-ef6c-494c-bcfa-d45d489d9506.png)
Black screen after shaking my phone (first-connection codeless app event)

```
[+9143 ms] E/SensorManager(27753): Exception dispatching input event.
[        ] D/AndroidRuntime(27753): Shutting down VM
[        ] E/AndroidRuntime(27753): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(27753): Process: com.myapp, PID: 27753
[        ] E/AndroidRuntime(27753): java.lang.NoSuchMethodError: No virtual method logSdkEvent(Ljava/lang/String;Ljava/lang/Double;Landroid/os/Bundle;)V in class Lcom/facebook/appevents/AppEventsLogger; or its super classes (declaration of 'com.facebook.appevents.AppEventsLogger' appears in /data/app/~~BcWvmFYZNUnVpLf9v8aGgw==/com.myapp-UlIfeAz5NpD-_NgRNjGK2A==/base.apk)
[        ] E/AndroidRuntime(27753): 	at com.facebook.marketing.internal.MarketingLogger.logGestureTriggered(MarketingLogger.java:66)
[        ] E/AndroidRuntime(27753): 	at com.facebook.marketing.CodelessActivityLifecycleTracker$1$1.onShake(CodelessActivityLifecycleTracker.java:100)
[        ] E/AndroidRuntime(27753): 	at com.facebook.marketing.ViewIndexingTrigger.onSensorChanged(ViewIndexingTrigger.java:76)
[        ] E/AndroidRuntime(27753): 	at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:856)
[        ] E/AndroidRuntime(27753): 	at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/AndroidRuntime(27753): 	at android.os.MessageQueue.next(MessageQueue.java:335)
[        ] E/AndroidRuntime(27753): 	at android.os.Looper.loop(Looper.java:193)
[        ] E/AndroidRuntime(27753): 	at android.app.ActivityThread.main(ActivityThread.java:7889)
[        ] E/AndroidRuntime(27753): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(27753): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
[        ] E/AndroidRuntime(27753): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```
---
### AndroidManifest.xml
```
...
 <application
        android:name=".Application"
        android:label="My App"
        android:icon="@mipmap/ic_launcher">

        <!-- [START fcm_default_channel] -->
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="high_importance_channel"/>

        <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
        <meta-data android:name="com.facebook.sdk.ClientToken" android:value="@string/facebook_client_token"/>

        //activity ...
</application>
...
```

### stringx.xml
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="default_notification_channel_id" translatable="false">firebase_messaging_background</string>
    <string name="facebook_app_id">xxx</string>
    <string name="fb_login_protocol_scheme">xxx</string>
    <string name="facebook_client_token">xxx</string>
</resources>
```

### build.gradle (project-level)
```
buildscript {
    ext.kotlin_version = '1.4.32'
    repositories {
        google()
        jcenter()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
}
...
```

### build.gradle (app-level)
```
...
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation platform('com.google.firebase:firebase-bom:25.12.0')
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.facebook.android:facebook-android-sdk:13.2.0'
    implementation 'com.facebook.android:facebook-marketing:4.35.0'
}
```

Am I missing some pieces?

**Comment by kingmaster772** [comment]
The error above disappear after I add this before `CodelessDebugLogEnabled` metadata

```
        <meta-data
            android:name="com.facebook.sdk.AutoLogAppEventsEnabled"
            android:value="false"/>
```

**Comment by NilaThasmiya** [comment]
Hi @agil3st Were you able to fix this?

**Comment by agil3st** [comment]
> Hi @agil3st Were you able to fix this? 

Not yet. maybe there is another approach but i'm not sure.
