### ISSUE TITLE
MissingPluginException for other packages when this package added

### ISSUE THREAD

**Issue by alectogeek** [oddbit/flutter_facebook_app_events#81]
When I added facebook_app_events to my project, it can't launch anymore.

Probably the same as for #52

Error:
```
Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
E/flutter (14275): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (14275): <asynchronous suspension>
E/flutter (14275): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (14275): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:345:41)
E/flutter (14275): #3      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:30:36)
E/flutter (14275): #4      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:75:13)
E/flutter (14275): #5      Firebase.initializeApp (package:firebase_core/src/firebase.dart:44:25)
E/flutter (14275): #6      main (package:finhelpapp/main.dart:18:18)
E/flutter (14275): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter (14275): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (14275): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (14275): #10     _runZoned (dart:async/zone.dart:1630:10)
E/flutter (14275): #11     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter (14275): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter (14275): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (14275): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

Flutter doctor:
```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-RU)
    • Flutter version 1.22.5 
    • Framework revision 7891006299 (8 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4
```

 pubspec.yaml packages:
```
...
  facebook_app_events: 0.8.2
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  firebase_crashlytics: ^0.4.0+1
  firebase_analytics: ^7.0.1
  firebase_remote_config: ^0.6.0
  firebase_database: ^6.0.0
...
```

**Comment by DennisAlund** [comment]
If you think it's the same as #52 I'll close it with a link to the solution, which was a user-configuration error 

https://github.com/oddbit/flutter_facebook_app_events/issues/52#issuecomment-690984118

**Comment by alectogeek** [comment]
@DennisAlund Yes, you were right. There is a typo in the documentation, so it didn't work from the first attempt. Then I removed the strings.xml file and directly wrote the id in the Manifest file and hit that error.
![image](https://user-images.githubusercontent.com/18165303/107356633-544d6700-6ad1-11eb-8110-5137699f116f.png)

**Comment by jnrbo** [comment]
Had the same error. Fixed moving meta-data outside **activity** to **application**

The file name is arbitrary as [documented](https://developer.android.com/guide/topics/resources/string-resource) so this isn't the problem.
